server:
  port: 10005

spring:
  cloud:
    stream:
#      kafka:
#        binder:
#          autoAddPartitions: true
      bindings:
        output:
          destination: polledConsumerOut
        input:
          destination: polledConsumerIn
          group: polledConsumerApplication
          content-type: text/plain
