server:
  port: 10015

spring:
  cloud:
    stream:
      instance-count: 1
      instance-index: 0
      bindings:
        input:
          destination: topic1
          group: myGroup
          content-type: text/plain