server:
  port: 10012

spring:
  cloud:
    stream:
      instance-count: 1
      instance-index: 0
      bindings:
        input:
          destination: partitioned.topic
          group: myGroup
          content-type: text/plain
          consumer:
            concurrency: 2
            partitioned: true
