server:
  port: 10004

spring:
  cloud:
    stream:
      bindings:
        output:
          destination: polledConsumerOut
        input:
          destination: polledConsumerIn
          group: polledConsumerApplication
          content-type: text/plain
